"""criar tabelas de anuncios e disponibilidades

Revision ID: 2b1adc1f82bb
Revises: e6e68fe4f3d3
Create Date: 2026-08-03 17:20:30.878174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1adc1f82bb'
down_revision = 'e6e68fe4f3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anuncios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('modalidade', sa.String(length=20), nullable=False),
    sa.Column('condicao', sa.String(length=30), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anuncio_disponibilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anuncio_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['anuncio_id'], ['anuncios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anuncio_disponibilidades')
    op.drop_table('anuncios')
    # ### end Alembic commands ###
