"""adiciona solicitacoes e notificacoes

Revision ID: 4bb702221db5
Revises: 3c7f5b9e21a4
Create Date: 2026-09-17 00:02:49.726690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4bb702221db5"
down_revision = "3c7f5b9e21a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "notificacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("titulo", sa.String(length=150), nullable=False),
        sa.Column("mensagem", sa.Text(), nullable=False),
        sa.Column("lida", sa.Boolean(), nullable=False),
        sa.Column("referencia_id", sa.Integer(), nullable=True),
        sa.Column("criada_em", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "solicitacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anuncio_id", sa.Integer(), nullable=False),
        sa.Column("interessado_id", sa.Integer(), nullable=False),
        sa.Column("disponibilidade_id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["anuncio_id"],
            ["anuncios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["disponibilidade_id"],
            ["anuncio_disponibilidades.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interessado_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table(
        "anuncio_disponibilidades",
        schema=None,
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.String(length=20),
                nullable=False,
                server_default="disponivel",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table(
        "anuncio_disponibilidades",
        schema=None,
    ) as batch_op:
        batch_op.drop_column("status")

    op.drop_table("solicitacoes")
    op.drop_table("notificacoes")

    # ### end Alembic commands ###