"""adiciona imagem de perfil ao usuario

Revision ID: 77df1584d732
Revises: a91e7d4c62f0
Create Date: 2026-09-26 18:39:44.897806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77df1584d732'
down_revision = 'a91e7d4c62f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_perfil', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('imagem_perfil')

    # ### end Alembic commands ###
