"""create cupons table

Revision ID: 92ab48208425
Revises: 9e03a74fec34
Create Date: 2026-09-30 22:36:17.567268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ab48208425'
down_revision = '9e03a74fec34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parceiro_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('imagem_url', sa.String(length=500), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('limite_resgates', sa.Integer(), nullable=True),
    sa.Column('validade_inicio', sa.DateTime(), nullable=False),
    sa.Column('validade_fim', sa.DateTime(), nullable=False),
    sa.Column('regras', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cupons_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_cupons_parceiro_id'), ['parceiro_id'], unique=False)

    with op.batch_alter_table('parceiros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.String(length=14), nullable=False))
        batch_op.create_unique_constraint(None, ['cnpj'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parceiros', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cnpj')

    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cupons_parceiro_id'))
        batch_op.drop_index(batch_op.f('ix_cupons_ativo'))

    op.drop_table('cupons')
    # ### end Alembic commands ###
