"""adiciona public id das imagens dos cupons

Revision ID: b0ddcf27f58a
Revises: 92ab48208425
Create Date: 2026-09-30 23:59:10.961837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ddcf27f58a'
down_revision = '92ab48208425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_public_id', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.drop_column('imagem_public_id')

    # ### end Alembic commands ###
